<center><h1> [[ Python tutorial AtoP ]] </h1></center>

# 1. Jupyter notebook

### 주피터노트북 주요 기능
- cell type : markdown / code
- [shift]+ [enter] : cell 실행 후 아래 cell 포커싱
- [alt] + [enter] : cell 실행 후 아래 새 cell 생성
- [tab] : 자동완성

### 초심자가 알아야하는 파이썬 기능
- help(~~)
- ?~~
- type(~~)

# 2. Basic Data type

## 1) Number

### i) 다양한 숫자형 데이터의 연산자

In [6]:
#덧셈
1+5

6

In [7]:
#뺄셈
5-10

-5

In [8]:
#곱셈
3*6

18

In [9]:
# 제곱
12**2

144

In [10]:
#나눗셈
13/4

3.25

In [11]:
#나눗셈...??
13//4

3

In [12]:
#...?!
13%4    #=> Modulo operation

1

### ii) 변수 : 값을 저장하는 공간. 

In [13]:
x = 5

In [14]:
y = 7

In [15]:
x+y

12

### Q) 다음의 결과는? 그리고 왜??

In [16]:
answer = ((5+5)*10)**(1+1)

In [17]:
answer

10000

## 2) String

In [18]:
# 문자열(String)은 "혹은 '로 만들 수 있음.
str1 = "This is an apple."
str2 = 'This is also an apple.'

In [19]:
str1

'This is an apple.'

In [20]:
str2

'This is also an apple.'

In [27]:
# 이건 왜 에러..??
"""" 'I"m a pythonista. """

'" \'I"m a pythonista. '

### Q) 위 문제의 해결방법은..?

In [32]:
str1

'This is an apple.'

In [30]:
str1[1]

'h'

In [31]:
str1[0:4]

'This'

In [37]:
str1[-6:-1]

'apple'

In [38]:
"string"+"string"

'stringstring'

In [39]:
"string"*3

'stringstringstring'

## 3) List 
- 리스트명 = [요소1, 요소2, 요소3, ...]

### i) 생성

In [42]:
odd = [1, 3, 5, 7, 9]
odd

[1, 3, 5, 7, 9]

In [41]:
[ ]

[]

In [43]:
[1, 2, 3]

[1, 2, 3]

In [44]:
[1, "a", "b"]

[1, 'a', 'b']

In [45]:
[1, 2, ['Life', 'is']]

[1, 2, ['Life', 'is']]

### ii) 값 접근

In [46]:
odd

[1, 3, 5, 7, 9]

In [47]:
odd[1]

3

In [48]:
odd[:3]

[1, 3, 5]

In [ ]:
odd[3:]

In [ ]:
# 값 변경
odd[3] = "a"

In [ ]:
odd

## 4) Tuple
- tuple명 = (요소1, 요소2, ...)
- list와 유사하지만 값 수정 불가

In [ ]:
t = (1, 2, 3)
t

In [ ]:
t[0]

In [ ]:
t[0]=100

## 5) Dictionary
- key: value 쌍으로 이루어진 데이터 타입
- {Key1:Value1, Key2:Value2, Key3:Value3 ...}

In [49]:
my_bag = {'pencil': 3, 'laptop':1, 'book': 5}
my_bag

{'book': 5, 'laptop': 1, 'pencil': 3}

In [50]:
my_bag["pencil"]

3

In [51]:
my_bag["pencil"] = 12

In [ ]:
my_bag

In [52]:
my_bag.keys()
#list(my_bag.keys())

dict_keys(['pencil', 'laptop', 'book'])

In [53]:
my_bag.values()

dict_values([12, 1, 5])

## 6) Set
- 집합을 처리하기 위해 만들어진 데이터 타입
- 특징 : __중복허용안함, 순서없음__
- set(~~~) 로 생성

In [54]:
s1 = set([1,2,3])
s1

{1, 2, 3}

In [55]:
s2 = set("Hello")
s2

{'H', 'e', 'l', 'o'}

In [56]:
# 값 추가
s2.add(6)
s2

{'e', 'H', 'l', 'o', 6}

In [ ]:
s2[1]

# 4. Numpy - Numerical Python
- [Numpy](http://www.numpy.org/): core library for scientific computing in Python.
- provides a high-performance multidimensional array object, and tools for working with these arrays

http://cs231n.github.io/python-numpy-tutorial/

### Numpy 에서 제공하는 기능
- 빠르고 메모리를 효율적으로 사용하며 벡터 산술연산과 세련된 브로드캐스팅 기능을 제공하는 다차원 배열 ndarray
- 반복문을 작성할 필요없이 전체 데이터 배열에 대해 빠른 연산을 제공하는 표준 수학 함수
- 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 올려진 파일을 사용하는 도구
- 선형대수, 난수 발생기, 푸리에 변환 기능.
- C, C++, 포트란으로 쓰여진 코드를 통합하는 도구.

### 패키지 불러오기
- import XXX
- import XXX as X
- from XXX import YYY
- from XXX import *

In [57]:
# Numpy 불러오기.
import numpy as np #=> numpy 패키지를 불러와서 np라는 이름으로 사용함. 기능을 사용할때마다 np.을 앞에 명시해야함.
#from numpy import * # => np. 없이 사용해도 괜찮음. 하지만 좋지않음..!

## 1) Arrays
- ndarray : 같은 종류를 담을 수 있는 포괄적인 다차원(N diemnsion) 배열 객체.
- 스칼라 원소 간의 연산에 사용하는 문법과 비슷한 방식을 사용해서 전체 데이터 블록에 수학적인 연산을 수행할 수 있게 함.
- __모든 원소는 같은 자료형 이어야함!__
- 모든 array는 각 차원의 크기를 알려주는 __shape__라는 튜플과 array에 저장된 자료형을 알려주는 __dtype__이라는 객체를 가지고 있음.

### i) 1차원 array

In [58]:
temp_list = [1,2,3]

In [59]:
arr = np.array(temp_list)

In [64]:
arr_ = arr.astype(str)

In [66]:
arr_

array(['1', '2', '3'],
      dtype='<U21')

In [72]:
arr

array([1, 2, 3])

In [61]:
# arr의 자료형 출력.
print(type(arr))

<class 'numpy.ndarray'>


In [62]:
# arr의 내부에 저장된 데이터의 자료형.
print(arr.dtype)
## => 명시적으로 지정하지 않으면, np.array가 생성될 때 적절한 자료형을 추정함.

int64


In [63]:
# arr의 차원.
print(arr.ndim)

1


In [ ]:
# arr의 모양을 튜플 형태로 보여줌.
print(arr.shape)

In [ ]:
# "[~~]" 를 이용해서 각각의 원소에 접근 가능.
print(arr[0])

In [ ]:
# 각각의 원소 출력.
print(arr[0],arr[1],arr[2])

In [ ]:
# arr의 0번째 원소에 접근하여 그 값에 5를 대입.
arr[0] = 5

In [ ]:
print(arr)

### ii) n차원 array

In [73]:
# 2차원 array 생성.
temp_list2 = [[1,2,3],[4,5,6],[7,8,9]]
arr2 = np.array(temp_list2)

In [74]:
temp_list2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [75]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [76]:
# arr2의 차원.
print(arr2.ndim)

2


In [77]:
# 3차원 array 생성.
temp_list3 = [[[1,2,3],[4,5,6],[7,8,9]],[[10,20,30],[40,50,60],[70,80,90]]]
arr3 = np.array(temp_list3)

In [78]:
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]


In [79]:
# arr3의 차원.
print(arr3.ndim)

3


### iii) Numpy 배열 생성 함수

In [80]:
# 모든 원소가 0이고, shape이 (5,5)인 ndarray 생성.
arr_zero = np.zeros((5,5))
print(arr_zero)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [81]:
print(arr_zero.shape)

(5, 5)


In [82]:
# 모든 원소가 1이고, shape이 (4,4)인 ndarray 생성.
arr_one = np.ones((4,4))
print(arr_one)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [83]:
# 모든 원소가 무작위이고, shape이 (4,4)인 ndarray 생성.
# np.random.random?
arr_rd = np.random.random((5,3))
print(arr_rd)

[[ 0.43788738  0.09544209  0.20164017]
 [ 0.91283058  0.99387673  0.06050545]
 [ 0.88741139  0.11203852  0.93106154]
 [ 0.66842743  0.63393681  0.87223563]
 [ 0.73877694  0.6885184   0.06270409]]


## 2) Array Indexing
- 파이썬 list와 유사하게 동작.

### i) Slicing

In [84]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [85]:
arr_slice = arr[:2,1:3]

In [86]:
print(arr_slice)

[[2 3]
 [6 7]]


In [87]:
print( arr[0,1] )

2


In [88]:
arr_slice[0,0] = 77
arr_slice

array([[77,  3],
       [ 6,  7]])

In [89]:
print( arr[0,1] )

77


## 3) Array math

### i) Basic mathematical functions 

In [90]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [91]:
print(x)
print(y)

[[ 1.  2.]
 [ 3.  4.]]
[[ 5.  6.]
 [ 7.  8.]]


In [92]:
# Elementwise sum
print(x + y)
print(np.add(x, y))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]


In [93]:
# Elementwise difference
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [94]:
# Elementwise product
print(x * y)
print( np.multiply(x, y))

[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]


In [95]:
# Elementwise division
print( x / y)
print( np.divide(x, y))

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [96]:
# Elementwise square root
print( np.sqrt(x))

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


### ii) dot product

In [97]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([1,2])
w = np.array([2,1])

In [98]:
# Inner product of vectors
print( v.dot(w) )
print( np.dot(v, w) )

4
4


In [99]:
# Matrix / vector product
print( x.dot(v) )
print( np.dot(x, v) )

[ 5 11]
[ 5 11]


In [100]:
# Matrix / matrix product
print( x.dot(y))
print( np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### iii) Useful function

In [101]:
x = np.array([[1,2],[3,4]])

In [102]:
# 모든 원소의 합
print( np.sum(x) )

10


In [103]:
# 각 col의 합
print( np.sum(x, axis=0)  )

[4 6]


In [104]:
# 각 row의 합
print( np.sum(x, axis=1)  )

[3 7]


In [105]:
# 틀린그림찾기!
print( x )
print( x.T ) # Transpose

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [ ]:
v = np.array([1,2,3])
print(v)

In [ ]:
print(v.T) #=> 1차원 array는 T가 안됨. (알아서 자동으로 처리하기 때문에 transpose가 무의미.)

<function ndarray.diagonal>

# 5. Pandas  - Data Analysis

In [110]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 1) Data Structure

In [111]:
from pandas import Series, DataFrame

### i) Series
- 1차원 list같은 자료구조.
- __index__에 각 데이터에 연관된 이름을 가지고 있음. -> id
- list로부터 생성가능.

In [112]:
obj = Series([4, 7, -5, 3])
print(obj)

0    4
1    7
2   -5
3    3
dtype: int64


In [113]:
# obj가 갖고 있는 데이터의 값 추출
obj.values

array([ 4,  7, -5,  3])

In [114]:
# obj가 갖고 있는 데이터의 index 추출
obj.index

RangeIndex(start=0, stop=4, step=1)

In [115]:
# index 임의로 지정 가능.
my_score = Series([93, 70, 96, 40], index=['Math', 'English', 'Science', 'Marketing'])
my_score

Math         93
English      70
Science      96
Marketing    40
dtype: int64

In [116]:
# obj2가 갖고 있는 데이터의 index 추출
my_score.index

Index(['Math', 'English', 'Science', 'Marketing'], dtype='object')

In [117]:
# 값에 접근할때는 index를 통해 접근.
my_score[2]

96

In [118]:
my_score['Math']

93

In [119]:
# 다수의 데이터에 접근할때는...
my_score['English','Marketing','Math']

KeyError: ('English', 'Marketing', 'Math')

In [120]:
# 없는 값에 접근하면...
my_score['Writing']

KeyError: 'Writing'

In [122]:
# 데이터 추가
my_score['Writing'] = 30

In [123]:
my_score

Math         93
English      70
Science      96
Marketing    40
Writing      30
dtype: int64

In [124]:
# 각 데이터에 산술연산 
my_score/10

Math         9.3
English      7.0
Science      9.6
Marketing    4.0
Writing      3.0
dtype: float64

In [125]:
# 특정 조건 데이터 추출 가능.
my_score[ my_score > 90 ]

Math       93
Science    96
dtype: int64

- 색인값에 데이터 값을 매핑하고 있으므로 파이썬의 사전형(dict)과 비슷

In [126]:
# 사전형처럼 사용 가능
'Math' in my_score

True

In [127]:
'Art' in my_score

False

In [131]:
# 사전형 객체로부터 Series 객체를 생성할 수도 있음!
your_score_dict = {"Math": 40, "English": 99, "Science":40, "Marketing":93}

In [ ]:
your_score_dict

### Q) your_score의 데이터타입이 뭔지 알고 싶을때는..?

In [132]:
your_score = Series(your_score_dict)
your_score
# => 데이터 정렬이 값의 내림차순으로 정렬됨!

English      99
Marketing    93
Math         40
Science      40
dtype: int64

In [ ]:
# index를 명시해서 문제해결.
your_score = Series(your_score_dict, index=['Math', 'English', 'Science', 'Marketing'])
your_score

In [128]:
my_score

Math         93
English      70
Science      96
Marketing    40
Writing      30
dtype: int64

### Q) my_score + your_score = ...?? 에러가 뜰까?

In [133]:
our_score = my_score + your_score

In [134]:
our_score

English      169.0
Marketing    133.0
Math         133.0
Science      136.0
Writing        NaN
dtype: float64

In [135]:
# .isnull() : 누락된 데이터인지 아닌지 판별.
our_score.isnull()

English      False
Marketing    False
Math         False
Science      False
Writing       True
dtype: bool

### ii) Dataframe
- R의 data.frame 같은 개념. -> __But.. Row와 Colomn에 대한 접근 개념이 반대.__
- 여러개의 column으로 이루어졌으며, 각 column은 서로 다른 종류의 값(숫자, 문자열, 불리언 등)을 담을 수 있음.
- 보통 같은 길이의 list에 담긴 사전형(dict)을 이용하거나 Numpy array를 이용함.

In [136]:
from pandas import DataFrame
import pandas as pd

In [137]:
score_data = {
    'Name':['윤아', '혜리', '민호', '수지'],
    'Class':['A', 'A', 'B', 'B'],
    'Gender':['F', 'F','M','F'],
    'Math':[100, 90, 70, 60],
    'English':[90, 90, 100, 70]
}

In [138]:
score_smf = DataFrame(score_data)

In [139]:
score_smf

Class  English Gender  Math Name
0     A       90      F   100   윤아
1     A       90      F    90   혜리
2     B      100      M    70   민호
3     B       70      F    60   수지

In [140]:
# column명 명시하여 순서 조절 가능.
score_smf = DataFrame(score_data, columns=['name','class','gender','Math','English'])
score_smf

name class gender  Math  English
0  NaN   NaN    NaN   100       90
1  NaN   NaN    NaN    90       90
2  NaN   NaN    NaN    70      100
3  NaN   NaN    NaN    60       70

In [141]:
# .info() : 해당 DataFrame에 대한 정보 보여줌.
score_smf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
name       0 non-null object
class      0 non-null object
gender     0 non-null object
Math       4 non-null int64
English    4 non-null int64
dtypes: int64(2), object(3)
memory usage: 240.0+ bytes


In [142]:
# 요약통계량
score_smf.describe()

Math     English
count    4.000000    4.000000
mean    80.000000   87.500000
std     18.257419   12.583057
min     60.000000   70.000000
25%     67.500000   85.000000
50%     80.000000   90.000000
75%     92.500000   92.500000
max    100.000000  100.000000

In [143]:
score_smf.describe(include='all')

name  class  gender        Math     English
count    0.0    0.0     0.0    4.000000    4.000000
unique   0.0    0.0     0.0         NaN         NaN
mean     NaN    NaN     NaN   80.000000   87.500000
std      NaN    NaN     NaN   18.257419   12.583057
min      NaN    NaN     NaN   60.000000   70.000000
25%      NaN    NaN     NaN   67.500000   85.000000
50%      NaN    NaN     NaN   80.000000   90.000000
75%      NaN    NaN     NaN   92.500000   92.500000
max      NaN    NaN     NaN  100.000000  100.000000

In [144]:
# column 접근 방법 1) : 사전형 데이터처럼 접근
score_smf['Math']

0    100
1     90
2     70
3     60
Name: Math, dtype: int64

In [145]:
# column 접근 방법 2) : 속성 형식으로 접근.
score_smf.Math

0    100
1     90
2     70
3     60
Name: Math, dtype: int64

### Q) R처럼 column에 접근할 수는 없을까? 

In [146]:
score_smf[1]

KeyError: 1

In [147]:
score_smf[1:3]

name class gender  Math  English
1  NaN   NaN    NaN    90       90
2  NaN   NaN    NaN    70      100

In [148]:
# row 접근 방법 : .iloc[~] 의 index로 접근 
score_smf.iloc[1]

name       NaN
class      NaN
gender     NaN
Math        90
English     90
Name: 1, dtype: object

In [149]:
# 새로운 column 추가
score_smf['isHuman'] = True
score_smf

name class gender  Math  English isHuman
0  NaN   NaN    NaN   100       90    True
1  NaN   NaN    NaN    90       90    True
2  NaN   NaN    NaN    70      100    True
3  NaN   NaN    NaN    60       70    True

In [153]:
# column 삭제
#del score_smf['isHuman']
score_smf

name class gender  Math  English
0  NaN   NaN    NaN   100       90
1  NaN   NaN    NaN    90       90
2  NaN   NaN    NaN    70      100
3  NaN   NaN    NaN    60       70

In [154]:
# 외부 데이터 로드
scores = pd.read_csv("data/scores.csv")
scores

Name Class Gender  Math  English
0  다니엘     C      M    90       60
1  제시카     C      F    80      100
2   태연     C      F    70       80
3   선미     D      F    80       90
4   강인     D      M    40       60
5   태양     D      M    80       90

In [155]:
# DataFrame.loc 으로 색인 [행이름 조건, 열이름 조건] 
scores.loc[:,:] #전부 
# scores.loc[:5,:] 
# scores.loc[:,'Math'] 
# scores.loc[:,['Math','English']]
# scores.loc[10:20,['Math','English']]

Name Class Gender  Math  English
0  다니엘     C      M    90       60
1  제시카     C      F    80      100
2   태연     C      F    70       80
3   선미     D      F    80       90
4   강인     D      M    40       60
5   태양     D      M    80       90

In [ ]:
# DataFrame.iloc으로 인덱스로 색인
# scores.iloc[:,:] # 전부
scores.iloc[1:5,2:5]